name: Build and Release App Bundle

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1.5.1

      - name: Build app bundle
        run: flutter build appbundle

      - name: Release app bundle
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/bundle/release/app.aab
          token: ${{ secrets.TOKEN }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Release for version ${{ github.ref }}
