name: Build and Release Release APK

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1.5.1

      - name: Build release APK
        run: flutter build apk --release

      - name: Release release APK
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.TOKEN }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Release for version ${{ github.ref }}
